#!/bin/bash
set -eux

# instantiate normal dependencies
julia --project=binder -e 'using Pkg; Pkg.instantiate()'

# install PlutoSliderServer from GitHub
julia --project=binder binder/PostBuild.jl

# check PlutoSliderServer works
julia --project=binder -e 'using PlutoSliderServer'
