name: Export Pluto Notebook

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: 1.11

      - name: Cache Julia artifacts
        uses: actions/cache@v4
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-julia-artifacts-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-artifacts-

      - name: Add exporter (PlutoSliderServer) just for CI
        run: julia -e 'using Pkg; Pkg.add("PlutoSliderServer")'

      - name: Make postBuild executable
        run: chmod +x binder/postBuild

      - name: Export notebook (HTML, plots, data) to ./out
        run: |
          julia --project=binder -e '
            using PlutoSliderServer
            PlutoSliderServer.export_notebook(
              "notebooks/index.jl";
              Export_output_dir = "out",
              Export_standalone = true,
              Export_create_index = true
            )'


      - name: Upload results as a build artifact (downloadable zip)
        uses: actions/upload-artifact@v4
        with:
          name: pluto-export
          path: out
